SET MODE DB2;

DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT
       (
              STUDENT_ID DOUBLE(53) NOT NULL,
              STUDENT_NAME VARCHAR(100) NOT NULL,
              COURSE_SCORE DOUBLE(53),
              COURSE_ID  DOUBLE(53) NOT NULL,
              CREATE_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
              LAST_MODIFIED_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
              PRIMARY KEY (STUDENT_ID)
              --CONSTRAINT COURSE FOREIGN KEY (COURSE_ID) REFERENCES "COURSE_ID" ("COURSE_ID") ON UPDATE NO ACTION ON DELETE RESTRICT
       );

DROP TABLE IF EXISTS COURSE;

CREATE TABLE COURSE
    (
        COURSE_ID DOUBLE(53) NOT NULL,
        COURSE_NAME VARCHAR(100) NOT NULL,
        CREATE_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        LAST_MODIFIED_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        PRIMARY KEY (COURSE_ID)
    );